//AUTHENTIFICATION TYPES
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';
export const GET_MANAGER = 'GET_MANAGER';
export const GET_USER = 'GET_USER';
export const UPDATE_INFO = 'UPDATE_INFO';
export const ERR_UPDATE_INFO = 'ERR_UPDATE_INFO';


//MANAGER EVENTS

export const CREATE_EVENT = 'CREATE_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const PUBLISH_EVENT = 'PUBISH_EVENT';
export const GET_EVENT = 'GET_EVENT';

